language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -qq cmake g++-4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - scripts/install_gtest.sh
  - scripts/install_ncurses.sh
before_script:
  - mkdir build
script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - tests/clecta-tests
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - armin.widegreen@gmail.com
    on_success: always
    on_failure: always
os:
  - linux
